### ISSUE TITLE
Bubble Sort Review

### ISSUE THREAD

**Issue by shpakkdv** [wheercool/evo-ts-bootcamp#2]
1. `NodeJS.Timeout` is incorrect. Try `window.setInterval` explicitly. [here](https://github.com/wheercool/evo-ts-bootcamp/blob/master/homeworks/01-bubble-sort/src/components/App/App.tsx#L27)
Also, `handle` is incorrect naming for interval id. It sounds like a function name. Functions start from a verb.

2. `algo` is bad naming ([here](https://github.com/wheercool/evo-ts-bootcamp/blob/master/homeworks/01-bubble-sort/src/components/App/App.tsx#L80)). It's really unreadable. Why not `algorithmName`?

3. [App](https://github.com/wheercool/evo-ts-bootcamp/blob/master/homeworks/01-bubble-sort/src/components/App/App.tsx) - why did you define access modifiers somewhere and somewhere didn't? I don't mean lifecycle methods.

4. [BarChart](https://github.com/wheercool/evo-ts-bootcamp/blob/master/homeworks/01-bubble-sort/src/components/BarChart/BarChart.tsx) can be Function (Stateless) Component.

5. Bad variable naming [here](https://github.com/wheercool/evo-ts-bootcamp/blob/master/homeworks/01-bubble-sort/src/models/algorithms.ts). Imagine the situation with much more complicated algorithms (someone else's code) and you should understand how it works and find a bug there or add some new logic. It's really unreadable: `xs`, `f`.

And why `algorithms.ts` located under the `models` folder. Is it correct?

**Comment by wheercool** [comment]
fixed
